/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NowPlaying {
  title: string
  artist: string
  album: string
  artDataUrl?: string
  positionMs: number
  durationMs: number
  lastUpdatedMs: number
  rate: number
  status: string
}
export declare function start(callback: (...args: any[]) => any): void
export declare function stop(): void
